title: DjangoCon US
url: "https://2011.djangocon.us"
author : DjangoCon US
enforce_ssl: "2011.djangocon.us"
relative_permalinks: false
permalink: news/:title/  # permalink: date

include:
  - _pages

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - '*.py'
  - '*.sh'
  - '*.txt'
  - '\?*'
  - .editorconfig
  - .gitignore
  - .surgeignore
  - _backup
  - bower_components
  - CNAME
  - CONTRIBUTING.md
  - deploy_surge.sh
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - Makefile
  - node_modules
  - package.json
  - Procfile
  - Rakefile
  - README.md

collections:  # process the _data folder
  components:
    output: false

# SEO Plugin settings

twitter:
  username: djangocon

# This is the default logo that people see with opengraph
logo: /static/2011-logos/squares-and-social/djangocon-square.png

# Frontmatter fallback settings
# This is the default logo that people see on blog posts
defaults:
  - scope:
      path: ""
    values:
      image: /static/2011-logos/squares-and-social/djangocon-square.png
