title: DjangoCon US
url: "https://2011.djangocon.us"
author : DjangoCon US
enforce_ssl: "2011.djangocon.us"
relative_permalinks: false
permalink: news/:title/  # permalink: date

include:
  - _pages

# Build settings
markdown: kramdown

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-mentions
- jekyll-paginate
- jekyll-redirect-from
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

exclude:
- "*.yaml"
- "*.yml"
- .cache
- .editorconfig
- .gitignore
- .vendor
- bin
- bower_components
- CNAME
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docker-compose.yml
- EDITORS_GUIDE.md
- Gemfile
- Gemfile.lock
- justfile
- LICENSE
- Makefile
- node_modules
- NOTES.md
- package*.json
- Procfile
- README.md
- requirements.in
- vendor
- webpack.config.js

collections:  # process the _data folder
  components:
    output: false

# SEO Plugin settings

twitter:
  username: djangocon

# This is the default logo that people see with opengraph
logo: /static/2011-logos/squares-and-social/djangocon-square.png

# Frontmatter fallback settings
# This is the default logo that people see on blog posts
defaults:
  - scope:
      path: ""
    values:
      image: /static/2011-logos/squares-and-social/djangocon-square.png

google_analytics: "UA-93279021-8"
